name: faucet build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ci-cd'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Version
        id: version_bump
        uses: anothrNick/github-tag-action@1.38.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DEFAULT_BUMP: "patch"
          RELEASE_BRANCHES: "master"
          WITH_V: true
      - name: Set access Keys
        run: echo "$SSH_KEY_GITHUB" > id_rsa
        env:
          SSH_KEY_GITHUB: ${{secrets.SSH_KEY_GITHUB}}
      - name: Docker
        run: |
          docker login ghcr.io -u ${{github.actor}} -p ${{secrets.GITHUB_TOKEN}}
          docker build -f Dockerfile -t ghcr.io/core-coin/faucet/faucet:${{steps.version_bump.outputs.tag}} -t ghcr.io/core-coin/faucet/faucet:latest .
          docker push --all-tags ghcr.io/core-coin/faucet/faucet
      - name: Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version_bump.outputs.tag }}
          release_name: faucet ${{ steps.version_bump.outputs.tag }}
          draft: false
          prerelease: false
