name: faucet build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ci-cd'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker
        run: |
          docker login ghcr.io -u ${{github.actor}} -p ${{secrets.GITHUB_TOKEN}}
          docker build -f Dockerfile -t ghcr.io/core-coin/faucet/faucet:latest .
          docker push --all-tags ghcr.io/core-coin/faucet/faucet
